### ISSUE TITLE
Python 3 exceptions are re-raised visible

### ISSUE THREAD

**Issue by sanand0** [sanand0/orderedattrdict#1]
Try this:

```
>>> from orderedattrdict import AttrDict
>>> ad = AttrDict()
>>> ad.missing
Traceback (most recent call last):
  File "D:\anaconda\3\lib\site-packages\orderedattrdict\__init__.py", line 25, in __getattr__
    return self[name]
KeyError: 'missing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda\3\lib\site-packages\orderedattrdict\__init__.py", line 27, in __getattr__
    raise AttributeError(name)
AttributeError: missing
```

See [six.reraise](https://pythonhosted.org/six/index.html#six.reraise)?

**Comment by sanand0** [comment]
This does not cause too much confusion. Closing for now.
